language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm test
  - npm run lint

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  chrome: stable